version: '3'
services:
  db-interview-app:
    image: postgres:15.1
    ports:
      - 5444:5432  # 5444 слушаем мы снаружи / 5432 - слушает внутри VM
    environment:
      POSTGRES_DB: "hack-interview"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "654321"
    restart: always # наш докер образ будет работать несмотря на перезагрузку машины